### ISSUE TITLE
Missing clarity in Readme file

### ISSUE THREAD

**Issue by Deepthi-R-Shetty** [Jithesh-poojary/BasicApiInAsp.net#1]
Listing, adding, updating, and deleting villa
Search and filtering capabilities
Flexible and extensible using dependency injection      This doesnt make any sense can you explain properly with correct examples.

**Comment by Jithesh-poojary** [comment]
Sure @Deepthi-R-Shetty  will give a proper documentation for this

**Comment by Jithesh-poojary** [comment]
Added Url based on request for more explaination
